# Generated by Django 5.1.7 on 2025-06-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('BLP_ID', models.CharField(db_column='BLP_ID', max_length=50)),
                ('TARIFF_ID', models.CharField(db_column='TARIFF_ID', max_length=50)),
                ('PACKAGE_NAME', models.CharField(db_column='PACKAGE_NAME', max_length=50)),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('CREATED_USER', models.CharField(blank=True, db_column='CREATED_USER', max_length=50, null=True)),
                ('UPDATED_DATE', models.DateTimeField(auto_now=True, db_column='UPDATED_DATE', null=True)),
                ('UPDATED_USER', models.CharField(blank=True, db_column='UPDATED_USER', max_length=50, null=True)),
                ('STATUS', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='STATUS', max_length=50)),
            ],
            options={
                'db_table': 'SIA_DL_BLACKLIST_PACKAGES',
            },
        ),
        migrations.CreateModel(
            name='PackageRate',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PACKAGE_RATE_ID', models.CharField(db_column='PACKAGE_RATE_ID', max_length=50)),
                ('TARIFF_ID', models.CharField(db_column='TARIFF_ID', max_length=50)),
                ('PACKAGE_NAME', models.CharField(db_column='PACKAGE_NAME', max_length=50)),
                ('COMPLIANCE', models.CharField(choices=[('P', 'PASS'), ('F', 'FAIL')], db_column='COMPLIANCE', max_length=1)),
                ('STAGE_LEVEL_STATUS_CHECK', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], db_column='STAGE_LEVEL_STATUS_CHECK', max_length=1)),
                ('SLAB_LEVEL_1_RATE', models.DecimalField(db_column='SLAB_LEVEL_1_RATE', decimal_places=2, max_digits=10)),
                ('BASE_RATE', models.DecimalField(db_column='BASE_RATE', decimal_places=2, max_digits=10)),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('CREATED_USER', models.CharField(blank=True, db_column='CREATED_USER', max_length=50, null=True)),
                ('UPDATED_DATE', models.DateTimeField(auto_now=True, db_column='UPDATED_DATE', null=True)),
                ('UPDATED_USER', models.CharField(blank=True, db_column='UPDATED_USER', max_length=50, null=True)),
                ('STATUS', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='STATUS', max_length=50)),
            ],
            options={
                'db_table': 'SIA_DL_PACKAGE_RATES',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('SCHEME_NUM', models.CharField(db_column='SCHEME_NUM', max_length=10)),
                ('SCHEME_NAME', models.CharField(db_column='SCHEME_NAME', max_length=50)),
                ('STATUS', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='STATUS', max_length=50)),
                ('START_DATE', models.DateField(blank=True, null=True)),
                ('ATTACHMENT', models.FileField(blank=True, null=True, upload_to='scheme_attachments/')),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('CREATED_USER', models.CharField(blank=True, db_column='CREATED_USER', max_length=50, null=True)),
                ('UPDATED_DATE', models.DateTimeField(auto_now=True, db_column='UPDATED_DATE', null=True)),
                ('UPDATED_USER', models.CharField(blank=True, db_column='UPDATED_USER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'SIA_DL_SCHEME',
            },
        ),
        migrations.CreateModel(
            name='SIA_DL_BEARER_RATE',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('SERVICE_TYPE', models.CharField(db_column='SERVICE_TYPE', max_length=50)),
                ('ORDER_TYPE', models.CharField(db_column='ORDER_TYPE', max_length=50)),
                ('COMPLIANCE', models.CharField(db_column='COMPLIANCE', default='P', max_length=1)),
                ('RATES_UNDER_SLAB_LEVELS', models.DecimalField(db_column='RATES_UNDER_SLAB_LEVELS', decimal_places=2, default=0, max_digits=10)),
                ('STATUS', models.CharField(db_column='STATUS', default='ACTIVE', max_length=50)),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('CREATED_USER', models.CharField(blank=True, db_column='CREATED_USER', max_length=50, null=True)),
                ('UPDATED_DATE', models.DateTimeField(auto_now=True, db_column='UPDATED_DATE', null=True)),
                ('UPDATED_USER', models.CharField(blank=True, db_column='UPDATED_USER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'SIA_DL_BEARER_RATE',
            },
        ),
        migrations.CreateModel(
            name='SlabLevel',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('SLAB_ID', models.CharField(db_column='SLAB_ID', max_length=50)),
                ('SLAB_LEVEL', models.CharField(db_column='SLAB_LEVEL', max_length=50)),
                ('UPPER_RANGE', models.DecimalField(db_column='UPPER_RANGE', decimal_places=2, max_digits=15)),
                ('LOWER_RANGE', models.DecimalField(db_column='LOWER_RANGE', decimal_places=2, max_digits=15)),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('CREATED_USER', models.CharField(blank=True, db_column='CREATED_USER', max_length=50, null=True)),
                ('UPDATED_DATE', models.DateTimeField(auto_now=True, db_column='UPDATED_DATE', null=True)),
                ('UPDATED_USER', models.CharField(blank=True, db_column='UPDATED_USER', max_length=50, null=True)),
                ('STATUS', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='STATUS', default='ACTIVE', max_length=50)),
            ],
            options={
                'db_table': 'SIA_DL_SLAB_LEVELS',
            },
        ),
        migrations.CreateModel(
            name='SO_TYPES',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('SO_TYPE_ID', models.CharField(db_column='SO_TYPE_ID', max_length=50)),
                ('PRODUCT', models.CharField(db_column='PRODUCT', max_length=50)),
                ('SERVICE_TYPE', models.CharField(db_column='SERVICE_TYPE', max_length=50)),
                ('ORDER_TYPE', models.CharField(db_column='ORDER_TYPE', max_length=50)),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('CREATED_USER', models.CharField(blank=True, db_column='CREATED_USER', max_length=50, null=True)),
                ('UPDATED_DATE', models.DateTimeField(auto_now=True, db_column='UPDATED_DATE', null=True)),
                ('UPDATED_USER', models.CharField(blank=True, db_column='UPDATED_USER', max_length=50, null=True)),
                ('STATUS', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], db_column='STATUS', max_length=50)),
            ],
            options={
                'db_table': 'SIA_DL_SO_TYPES',
            },
        ),
        migrations.CreateModel(
            name='SchemeRule',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('SCHEME_NUM', models.CharField(db_column='SCHEME_NUM', max_length=50)),
                ('TABLE_NAME', models.CharField(db_column='TABLE_NAME', max_length=50)),
                ('RT_ID', models.CharField(db_column='RT_ID', max_length=100)),
                ('SCHEME', models.ForeignKey(db_column='SCHEME_ID', on_delete=django.db.models.deletion.CASCADE, related_name='RULES_BY_ID', to='dealer_module.scheme')),
            ],
            options={
                'db_table': 'SIA_DL_SCHEME_RULES',
                'indexes': [models.Index(fields=['SCHEME'], name='SIA_DL_SCHE_SCHEME__047e19_idx'), models.Index(fields=['SCHEME_NUM'], name='SIA_DL_SCHE_SCHEME__51961a_idx')],
            },
        ),
    ]
